version: "3.9"
services:
  postgres:
    image: postgres:12
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=Aa123456
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


